/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: subframe2file.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "subframe2file.pb-c.h"
void   gps_fix__init
                     (GpsFix         *message)
{
  static const GpsFix init_value = GPS_FIX__INIT;
  *message = init_value;
}
size_t gps_fix__get_packed_size
                     (const GpsFix *message)
{
  assert(message->base.descriptor == &gps_fix__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gps_fix__pack
                     (const GpsFix *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gps_fix__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gps_fix__pack_to_buffer
                     (const GpsFix *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gps_fix__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GpsFix *
       gps_fix__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GpsFix *)
     protobuf_c_message_unpack (&gps_fix__descriptor,
                                allocator, len, data);
}
void   gps_fix__free_unpacked
                     (GpsFix *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gps_fix__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gps_data__init
                     (GpsData         *message)
{
  static const GpsData init_value = GPS_DATA__INIT;
  *message = init_value;
}
size_t gps_data__get_packed_size
                     (const GpsData *message)
{
  assert(message->base.descriptor == &gps_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gps_data__pack
                     (const GpsData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gps_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gps_data__pack_to_buffer
                     (const GpsData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gps_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GpsData *
       gps_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GpsData *)
     protobuf_c_message_unpack (&gps_data__descriptor,
                                allocator, len, data);
}
void   gps_data__free_unpacked
                     (GpsData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gps_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gps_info__init
                     (GpsInfo         *message)
{
  static const GpsInfo init_value = GPS_INFO__INIT;
  *message = init_value;
}
size_t gps_info__get_packed_size
                     (const GpsInfo *message)
{
  assert(message->base.descriptor == &gps_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gps_info__pack
                     (const GpsInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gps_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gps_info__pack_to_buffer
                     (const GpsInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gps_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GpsInfo *
       gps_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GpsInfo *)
     protobuf_c_message_unpack (&gps_info__descriptor,
                                allocator, len, data);
}
void   gps_info__free_unpacked
                     (GpsInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gps_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rssi_data__init
                     (RssiData         *message)
{
  static const RssiData init_value = RSSI_DATA__INIT;
  *message = init_value;
}
size_t rssi_data__get_packed_size
                     (const RssiData *message)
{
  assert(message->base.descriptor == &rssi_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rssi_data__pack
                     (const RssiData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rssi_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rssi_data__pack_to_buffer
                     (const RssiData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rssi_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RssiData *
       rssi_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RssiData *)
     protobuf_c_message_unpack (&rssi_data__descriptor,
                                allocator, len, data);
}
void   rssi_data__free_unpacked
                     (RssiData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rssi_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rssi_val__init
                     (RssiVal         *message)
{
  static const RssiVal init_value = RSSI_VAL__INIT;
  *message = init_value;
}
size_t rssi_val__get_packed_size
                     (const RssiVal *message)
{
  assert(message->base.descriptor == &rssi_val__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rssi_val__pack
                     (const RssiVal *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rssi_val__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rssi_val__pack_to_buffer
                     (const RssiVal *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rssi_val__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RssiVal *
       rssi_val__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RssiVal *)
     protobuf_c_message_unpack (&rssi_val__descriptor,
                                allocator, len, data);
}
void   rssi_val__free_unpacked
                     (RssiVal *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rssi_val__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   phich_config_common__init
                     (PhichConfigCommon         *message)
{
  static const PhichConfigCommon init_value = PHICH_CONFIG_COMMON__INIT;
  *message = init_value;
}
size_t phich_config_common__get_packed_size
                     (const PhichConfigCommon *message)
{
  assert(message->base.descriptor == &phich_config_common__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t phich_config_common__pack
                     (const PhichConfigCommon *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &phich_config_common__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t phich_config_common__pack_to_buffer
                     (const PhichConfigCommon *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &phich_config_common__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PhichConfigCommon *
       phich_config_common__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PhichConfigCommon *)
     protobuf_c_message_unpack (&phich_config_common__descriptor,
                                allocator, len, data);
}
void   phich_config_common__free_unpacked
                     (PhichConfigCommon *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &phich_config_common__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   phich_reg__init
                     (PhichReg         *message)
{
  static const PhichReg init_value = PHICH_REG__INIT;
  *message = init_value;
}
size_t phich_reg__get_packed_size
                     (const PhichReg *message)
{
  assert(message->base.descriptor == &phich_reg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t phich_reg__pack
                     (const PhichReg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &phich_reg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t phich_reg__pack_to_buffer
                     (const PhichReg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &phich_reg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PhichReg *
       phich_reg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PhichReg *)
     protobuf_c_message_unpack (&phich_reg__descriptor,
                                allocator, len, data);
}
void   phich_reg__free_unpacked
                     (PhichReg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &phich_reg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   frameparms__init
                     (Frameparms         *message)
{
  static const Frameparms init_value = FRAMEPARMS__INIT;
  *message = init_value;
}
size_t frameparms__get_packed_size
                     (const Frameparms *message)
{
  assert(message->base.descriptor == &frameparms__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t frameparms__pack
                     (const Frameparms *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &frameparms__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t frameparms__pack_to_buffer
                     (const Frameparms *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &frameparms__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Frameparms *
       frameparms__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Frameparms *)
     protobuf_c_message_unpack (&frameparms__descriptor,
                                allocator, len, data);
}
void   frameparms__free_unpacked
                     (Frameparms *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &frameparms__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mbsfn_config__init
                     (MbsfnConfig         *message)
{
  static const MbsfnConfig init_value = MBSFN_CONFIG__INIT;
  *message = init_value;
}
size_t mbsfn_config__get_packed_size
                     (const MbsfnConfig *message)
{
  assert(message->base.descriptor == &mbsfn_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mbsfn_config__pack
                     (const MbsfnConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mbsfn_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mbsfn_config__pack_to_buffer
                     (const MbsfnConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mbsfn_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MbsfnConfig *
       mbsfn_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MbsfnConfig *)
     protobuf_c_message_unpack (&mbsfn_config__descriptor,
                                allocator, len, data);
}
void   mbsfn_config__free_unpacked
                     (MbsfnConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mbsfn_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lte_data__init
                     (LteData         *message)
{
  static const LteData init_value = LTE_DATA__INIT;
  *message = init_value;
}
size_t lte_data__get_packed_size
                     (const LteData *message)
{
  assert(message->base.descriptor == &lte_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lte_data__pack
                     (const LteData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lte_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lte_data__pack_to_buffer
                     (const LteData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lte_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LteData *
       lte_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LteData *)
     protobuf_c_message_unpack (&lte_data__descriptor,
                                allocator, len, data);
}
void   lte_data__free_unpacked
                     (LteData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lte_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lte_ue_common__init
                     (LteUeCommon         *message)
{
  static const LteUeCommon init_value = LTE_UE_COMMON__INIT;
  *message = init_value;
}
size_t lte_ue_common__get_packed_size
                     (const LteUeCommon *message)
{
  assert(message->base.descriptor == &lte_ue_common__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lte_ue_common__pack
                     (const LteUeCommon *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lte_ue_common__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lte_ue_common__pack_to_buffer
                     (const LteUeCommon *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lte_ue_common__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LteUeCommon *
       lte_ue_common__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LteUeCommon *)
     protobuf_c_message_unpack (&lte_ue_common__descriptor,
                                allocator, len, data);
}
void   lte_ue_common__free_unpacked
                     (LteUeCommon *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lte_ue_common__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ue_proc__init
                     (UeProc         *message)
{
  static const UeProc init_value = UE_PROC__INIT;
  *message = init_value;
}
size_t ue_proc__get_packed_size
                     (const UeProc *message)
{
  assert(message->base.descriptor == &ue_proc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ue_proc__pack
                     (const UeProc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ue_proc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ue_proc__pack_to_buffer
                     (const UeProc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ue_proc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UeProc *
       ue_proc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UeProc *)
     protobuf_c_message_unpack (&ue_proc__descriptor,
                                allocator, len, data);
}
void   ue_proc__free_unpacked
                     (UeProc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ue_proc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   phy_vars_ue__init
                     (PhyVarsUe         *message)
{
  static const PhyVarsUe init_value = PHY_VARS_UE__INIT;
  *message = init_value;
}
size_t phy_vars_ue__get_packed_size
                     (const PhyVarsUe *message)
{
  assert(message->base.descriptor == &phy_vars_ue__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t phy_vars_ue__pack
                     (const PhyVarsUe *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &phy_vars_ue__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t phy_vars_ue__pack_to_buffer
                     (const PhyVarsUe *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &phy_vars_ue__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PhyVarsUe *
       phy_vars_ue__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PhyVarsUe *)
     protobuf_c_message_unpack (&phy_vars_ue__descriptor,
                                allocator, len, data);
}
void   phy_vars_ue__free_unpacked
                     (PhyVarsUe *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &phy_vars_ue__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ue_rx_tx_proc__init
                     (UeRxTxProc         *message)
{
  static const UeRxTxProc init_value = UE_RX_TX_PROC__INIT;
  *message = init_value;
}
size_t ue_rx_tx_proc__get_packed_size
                     (const UeRxTxProc *message)
{
  assert(message->base.descriptor == &ue_rx_tx_proc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ue_rx_tx_proc__pack
                     (const UeRxTxProc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ue_rx_tx_proc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ue_rx_tx_proc__pack_to_buffer
                     (const UeRxTxProc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ue_rx_tx_proc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UeRxTxProc *
       ue_rx_tx_proc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UeRxTxProc *)
     protobuf_c_message_unpack (&ue_rx_tx_proc__descriptor,
                                allocator, len, data);
}
void   ue_rx_tx_proc__free_unpacked
                     (UeRxTxProc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ue_rx_tx_proc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rx_tx_thread_data__init
                     (RxTxThreadData         *message)
{
  static const RxTxThreadData init_value = RX_TX_THREAD_DATA__INIT;
  *message = init_value;
}
size_t rx_tx_thread_data__get_packed_size
                     (const RxTxThreadData *message)
{
  assert(message->base.descriptor == &rx_tx_thread_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rx_tx_thread_data__pack
                     (const RxTxThreadData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rx_tx_thread_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rx_tx_thread_data__pack_to_buffer
                     (const RxTxThreadData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rx_tx_thread_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RxTxThreadData *
       rx_tx_thread_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RxTxThreadData *)
     protobuf_c_message_unpack (&rx_tx_thread_data__descriptor,
                                allocator, len, data);
}
void   rx_tx_thread_data__free_unpacked
                     (RxTxThreadData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rx_tx_thread_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue gps_fix__mode__enum_values_by_number[4] =
{
  { "MODE_NOT_SEEN", "GPS_FIX__MODE__MODE_NOT_SEEN", 0 },
  { "MODE_NO_FIX", "GPS_FIX__MODE__MODE_NO_FIX", 1 },
  { "MODE_2D", "GPS_FIX__MODE__MODE_2D", 2 },
  { "MODE_3D", "GPS_FIX__MODE__MODE_3D", 3 },
};
static const ProtobufCIntRange gps_fix__mode__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex gps_fix__mode__enum_values_by_name[4] =
{
  { "MODE_2D", 2 },
  { "MODE_3D", 3 },
  { "MODE_NOT_SEEN", 0 },
  { "MODE_NO_FIX", 1 },
};
const ProtobufCEnumDescriptor gps_fix__mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "GpsFix.Mode",
  "Mode",
  "GpsFix__Mode",
  "",
  4,
  gps_fix__mode__enum_values_by_number,
  4,
  gps_fix__mode__enum_values_by_name,
  1,
  gps_fix__mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor gps_fix__field_descriptors[15] =
{
  {
    "time",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(GpsFix, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(GpsFix, mode),
    &gps_fix__mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ept",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(GpsFix, ept),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "latitude",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(GpsFix, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "epy",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(GpsFix, epy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(GpsFix, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "epx",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(GpsFix, epx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "altitude",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(GpsFix, altitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "epv",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(GpsFix, epv),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "track",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(GpsFix, track),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "epd",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(GpsFix, epd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(GpsFix, speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eps",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(GpsFix, eps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "climb",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(GpsFix, climb),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "epc",
    15,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(GpsFix, epc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gps_fix__field_indices_by_name[] = {
  7,   /* field[7] = altitude */
  13,   /* field[13] = climb */
  14,   /* field[14] = epc */
  10,   /* field[10] = epd */
  12,   /* field[12] = eps */
  2,   /* field[2] = ept */
  8,   /* field[8] = epv */
  6,   /* field[6] = epx */
  4,   /* field[4] = epy */
  3,   /* field[3] = latitude */
  5,   /* field[5] = longitude */
  1,   /* field[1] = mode */
  11,   /* field[11] = speed */
  0,   /* field[0] = time */
  9,   /* field[9] = track */
};
static const ProtobufCIntRange gps_fix__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 15 }
};
const ProtobufCMessageDescriptor gps_fix__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GpsFix",
  "GpsFix",
  "GpsFix",
  "",
  sizeof(GpsFix),
  15,
  gps_fix__field_descriptors,
  gps_fix__field_indices_by_name,
  1,  gps_fix__number_ranges,
  (ProtobufCMessageInit) gps_fix__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gps_data__field_descriptors[5] =
{
  {
    "gps_fix",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GpsData, gps_fix),
    &gps_fix__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(GpsData, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "satellites_used",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(GpsData, satellites_used),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "satellites_visible",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(GpsData, satellites_visible),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gps_unix_time",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(GpsData, gps_unix_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gps_data__field_indices_by_name[] = {
  0,   /* field[0] = gps_fix */
  4,   /* field[4] = gps_unix_time */
  2,   /* field[2] = satellites_used */
  3,   /* field[3] = satellites_visible */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange gps_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor gps_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GpsData",
  "GpsData",
  "GpsData",
  "",
  sizeof(GpsData),
  5,
  gps_data__field_descriptors,
  gps_data__field_indices_by_name,
  1,  gps_data__number_ranges,
  (ProtobufCMessageInit) gps_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gps_info__field_descriptors[2] =
{
  {
    "gps_data",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GpsInfo, n_gps_data),
    offsetof(GpsInfo, gps_data),
    &gps_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi_container",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GpsInfo, rssi_container),
    &rssi_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gps_info__field_indices_by_name[] = {
  0,   /* field[0] = gps_data */
  1,   /* field[1] = rssi_container */
};
static const ProtobufCIntRange gps_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gps_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GpsInfo",
  "GpsInfo",
  "GpsInfo",
  "",
  sizeof(GpsInfo),
  2,
  gps_info__field_descriptors,
  gps_info__field_indices_by_name,
  1,  gps_info__number_ranges,
  (ProtobufCMessageInit) gps_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rssi_data__field_descriptors[1] =
{
  {
    "rssi_data",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RssiData, n_rssi_data),
    offsetof(RssiData, rssi_data),
    &rssi_val__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rssi_data__field_indices_by_name[] = {
  0,   /* field[0] = rssi_data */
};
static const ProtobufCIntRange rssi_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rssi_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RssiData",
  "RssiData",
  "RssiData",
  "",
  sizeof(RssiData),
  1,
  rssi_data__field_descriptors,
  rssi_data__field_indices_by_name,
  1,  rssi_data__number_ranges,
  (ProtobufCMessageInit) rssi_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rssi_val__field_descriptors[2] =
{
  {
    "rssi_val",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(RssiVal, n_rssi_val),
    offsetof(RssiVal, rssi_val),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi_unix_time",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(RssiVal, rssi_unix_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rssi_val__field_indices_by_name[] = {
  1,   /* field[1] = rssi_unix_time */
  0,   /* field[0] = rssi_val */
};
static const ProtobufCIntRange rssi_val__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rssi_val__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RssiVal",
  "RssiVal",
  "RssiVal",
  "",
  sizeof(RssiVal),
  2,
  rssi_val__field_descriptors,
  rssi_val__field_indices_by_name,
  1,  rssi_val__number_ranges,
  (ProtobufCMessageInit) rssi_val__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue phich_config_common__phich_duration__enum_values_by_number[2] =
{
  { "normal", "PHICH_CONFIG_COMMON__PHICH_DURATION__normal", 0 },
  { "extended", "PHICH_CONFIG_COMMON__PHICH_DURATION__extended", 1 },
};
static const ProtobufCIntRange phich_config_common__phich_duration__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex phich_config_common__phich_duration__enum_values_by_name[2] =
{
  { "extended", 1 },
  { "normal", 0 },
};
const ProtobufCEnumDescriptor phich_config_common__phich_duration__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "PhichConfigCommon.PhichDuration",
  "PhichDuration",
  "PhichConfigCommon__PhichDuration",
  "",
  2,
  phich_config_common__phich_duration__enum_values_by_number,
  2,
  phich_config_common__phich_duration__enum_values_by_name,
  1,
  phich_config_common__phich_duration__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue phich_config_common__phich_resource__enum_values_by_number[4] =
{
  { "oneSixth", "PHICH_CONFIG_COMMON__PHICH_RESOURCE__oneSixth", 1 },
  { "half", "PHICH_CONFIG_COMMON__PHICH_RESOURCE__half", 3 },
  { "one", "PHICH_CONFIG_COMMON__PHICH_RESOURCE__one", 6 },
  { "two", "PHICH_CONFIG_COMMON__PHICH_RESOURCE__two", 12 },
};
static const ProtobufCIntRange phich_config_common__phich_resource__value_ranges[] = {
{1, 0},{3, 1},{6, 2},{12, 3},{0, 4}
};
static const ProtobufCEnumValueIndex phich_config_common__phich_resource__enum_values_by_name[4] =
{
  { "half", 1 },
  { "one", 2 },
  { "oneSixth", 0 },
  { "two", 3 },
};
const ProtobufCEnumDescriptor phich_config_common__phich_resource__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "PhichConfigCommon.PhichResource",
  "PhichResource",
  "PhichConfigCommon__PhichResource",
  "",
  4,
  phich_config_common__phich_resource__enum_values_by_number,
  4,
  phich_config_common__phich_resource__enum_values_by_name,
  4,
  phich_config_common__phich_resource__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor phich_config_common__field_descriptors[2] =
{
  {
    "phich_duration",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(PhichConfigCommon, phich_duration),
    &phich_config_common__phich_duration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phich_resource",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(PhichConfigCommon, phich_resource),
    &phich_config_common__phich_resource__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned phich_config_common__field_indices_by_name[] = {
  0,   /* field[0] = phich_duration */
  1,   /* field[1] = phich_resource */
};
static const ProtobufCIntRange phich_config_common__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor phich_config_common__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PhichConfigCommon",
  "PhichConfigCommon",
  "PhichConfigCommon",
  "",
  sizeof(PhichConfigCommon),
  2,
  phich_config_common__field_descriptors,
  phich_config_common__field_indices_by_name,
  1,  phich_config_common__number_ranges,
  (ProtobufCMessageInit) phich_config_common__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor phich_reg__field_descriptors[1] =
{
  {
    "phich_reg_inner",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(PhichReg, n_phich_reg_inner),
    offsetof(PhichReg, phich_reg_inner),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned phich_reg__field_indices_by_name[] = {
  0,   /* field[0] = phich_reg_inner */
};
static const ProtobufCIntRange phich_reg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor phich_reg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PhichReg",
  "PhichReg",
  "PhichReg",
  "",
  sizeof(PhichReg),
  1,
  phich_reg__field_descriptors,
  phich_reg__field_indices_by_name,
  1,  phich_reg__number_ranges,
  (ProtobufCMessageInit) phich_reg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue frameparms__lte_prefix_type__enum_values_by_number[2] =
{
  { "NORMAL", "FRAMEPARMS__LTE_PREFIX_TYPE__NORMAL", 0 },
  { "EXTENDED", "FRAMEPARMS__LTE_PREFIX_TYPE__EXTENDED", 1 },
};
static const ProtobufCIntRange frameparms__lte_prefix_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex frameparms__lte_prefix_type__enum_values_by_name[2] =
{
  { "EXTENDED", 1 },
  { "NORMAL", 0 },
};
const ProtobufCEnumDescriptor frameparms__lte_prefix_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Frameparms.LtePrefixType",
  "LtePrefixType",
  "Frameparms__LtePrefixType",
  "",
  2,
  frameparms__lte_prefix_type__enum_values_by_number,
  2,
  frameparms__lte_prefix_type__enum_values_by_name,
  1,
  frameparms__lte_prefix_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue frameparms__lte_frame_type__enum_values_by_number[2] =
{
  { "FDD", "FRAMEPARMS__LTE_FRAME_TYPE__FDD", 0 },
  { "TDD", "FRAMEPARMS__LTE_FRAME_TYPE__TDD", 1 },
};
static const ProtobufCIntRange frameparms__lte_frame_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex frameparms__lte_frame_type__enum_values_by_name[2] =
{
  { "FDD", 0 },
  { "TDD", 1 },
};
const ProtobufCEnumDescriptor frameparms__lte_frame_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Frameparms.LteFrameType",
  "LteFrameType",
  "Frameparms__LteFrameType",
  "",
  2,
  frameparms__lte_frame_type__enum_values_by_number,
  2,
  frameparms__lte_frame_type__enum_values_by_name,
  1,
  frameparms__lte_frame_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor frameparms__field_descriptors[29] =
{
  {
    "N_RB_DL",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Frameparms, n_rb_dl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "N_RB_UL",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Frameparms, n_rb_ul),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Nid_cell",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Frameparms, nid_cell),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Nid_cell_mbsfn",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Frameparms, nid_cell_mbsfn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Ncp",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Frameparms, ncp),
    &frameparms__lte_prefix_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Ncp_UL",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Frameparms, ncp_ul),
    &frameparms__lte_prefix_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nushift",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Frameparms, nushift),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frame_type",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Frameparms, frame_type),
    &frameparms__lte_frame_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tdd_config",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Frameparms, tdd_config),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tdd_config_S",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Frameparms, tdd_config_s),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "srsX",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Frameparms, srsx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node_id",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Frameparms, node_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freq_idx",
    15,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Frameparms, freq_idx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode1_flag",
    25,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Frameparms, mode1_flag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "threequarter_fs",
    26,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Frameparms, threequarter_fs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dl_symbols_in_S_subframe",
    33,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Frameparms, dl_symbols_in_s_subframe),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ul_symbols_in_S_subframe",
    34,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Frameparms, ul_symbols_in_s_subframe),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nb_antennas_tx",
    35,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Frameparms, nb_antennas_tx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nb_antennas_rx",
    36,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Frameparms, nb_antennas_rx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nb_antenna_ports_eNB",
    37,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Frameparms, nb_antenna_ports_enb),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phich_config_common",
    42,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Frameparms, phich_config_common),
    &phich_config_common__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_MBSFN_config",
    45,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Frameparms, num_mbsfn_config),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "MBSFN_config",
    46,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Frameparms, n_mbsfn_config),
    offsetof(Frameparms, mbsfn_config),
    &mbsfn_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxHARQ_Msg3Tx",
    47,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Frameparms, maxharq_msg3tx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SIwindowsize",
    48,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Frameparms, siwindowsize),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "SIPeriod",
    49,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Frameparms, siperiod),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pcfich_reg",
    50,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Frameparms, n_pcfich_reg),
    offsetof(Frameparms, pcfich_reg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pcfich_first_reg_idx",
    51,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Frameparms, pcfich_first_reg_idx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phich_reg_outer",
    52,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Frameparms, n_phich_reg_outer),
    offsetof(Frameparms, phich_reg_outer),
    &phich_reg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned frameparms__field_indices_by_name[] = {
  22,   /* field[22] = MBSFN_config */
  0,   /* field[0] = N_RB_DL */
  1,   /* field[1] = N_RB_UL */
  4,   /* field[4] = Ncp */
  5,   /* field[5] = Ncp_UL */
  2,   /* field[2] = Nid_cell */
  3,   /* field[3] = Nid_cell_mbsfn */
  25,   /* field[25] = SIPeriod */
  24,   /* field[24] = SIwindowsize */
  15,   /* field[15] = dl_symbols_in_S_subframe */
  7,   /* field[7] = frame_type */
  12,   /* field[12] = freq_idx */
  23,   /* field[23] = maxHARQ_Msg3Tx */
  13,   /* field[13] = mode1_flag */
  19,   /* field[19] = nb_antenna_ports_eNB */
  18,   /* field[18] = nb_antennas_rx */
  17,   /* field[17] = nb_antennas_tx */
  11,   /* field[11] = node_id */
  21,   /* field[21] = num_MBSFN_config */
  6,   /* field[6] = nushift */
  27,   /* field[27] = pcfich_first_reg_idx */
  26,   /* field[26] = pcfich_reg */
  20,   /* field[20] = phich_config_common */
  28,   /* field[28] = phich_reg_outer */
  10,   /* field[10] = srsX */
  8,   /* field[8] = tdd_config */
  9,   /* field[9] = tdd_config_S */
  14,   /* field[14] = threequarter_fs */
  16,   /* field[16] = ul_symbols_in_S_subframe */
};
static const ProtobufCIntRange frameparms__number_ranges[6 + 1] =
{
  { 1, 0 },
  { 5, 2 },
  { 25, 13 },
  { 33, 15 },
  { 42, 20 },
  { 45, 21 },
  { 0, 29 }
};
const ProtobufCMessageDescriptor frameparms__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Frameparms",
  "Frameparms",
  "Frameparms",
  "",
  sizeof(Frameparms),
  29,
  frameparms__field_descriptors,
  frameparms__field_indices_by_name,
  6,  frameparms__number_ranges,
  (ProtobufCMessageInit) frameparms__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mbsfn_config__field_descriptors[4] =
{
  {
    "radioframeAllocationPeriod",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MbsfnConfig, radioframeallocationperiod),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "radioframeAllocationOffset",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MbsfnConfig, radioframeallocationoffset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fourFrames_flag",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MbsfnConfig, fourframes_flag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mbsfn_SubframeConfig",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MbsfnConfig, mbsfn_subframeconfig),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mbsfn_config__field_indices_by_name[] = {
  2,   /* field[2] = fourFrames_flag */
  3,   /* field[3] = mbsfn_SubframeConfig */
  1,   /* field[1] = radioframeAllocationOffset */
  0,   /* field[0] = radioframeAllocationPeriod */
};
static const ProtobufCIntRange mbsfn_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor mbsfn_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MbsfnConfig",
  "MbsfnConfig",
  "MbsfnConfig",
  "",
  sizeof(MbsfnConfig),
  4,
  mbsfn_config__field_descriptors,
  mbsfn_config__field_indices_by_name,
  1,  mbsfn_config__number_ranges,
  (ProtobufCMessageInit) mbsfn_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lte_data__field_descriptors[1] =
{
  {
    "lte_data",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(LteData, n_lte_data),
    offsetof(LteData, lte_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lte_data__field_indices_by_name[] = {
  0,   /* field[0] = lte_data */
};
static const ProtobufCIntRange lte_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor lte_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LteData",
  "LteData",
  "LteData",
  "",
  sizeof(LteData),
  1,
  lte_data__field_descriptors,
  lte_data__field_indices_by_name,
  1,  lte_data__number_ranges,
  (ProtobufCMessageInit) lte_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lte_ue_common__field_descriptors[4] =
{
  {
    "rxdata",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LteUeCommon, n_rxdata),
    offsetof(LteUeCommon, rxdata),
    &lte_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sync_corr",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(LteUeCommon, n_sync_corr),
    offsetof(LteUeCommon, sync_corr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freq_offset",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LteUeCommon, freq_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eNb_id",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LteUeCommon, enb_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lte_ue_common__field_indices_by_name[] = {
  3,   /* field[3] = eNb_id */
  2,   /* field[2] = freq_offset */
  0,   /* field[0] = rxdata */
  1,   /* field[1] = sync_corr */
};
static const ProtobufCIntRange lte_ue_common__number_ranges[2 + 1] =
{
  { 3, 0 },
  { 5, 1 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor lte_ue_common__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LteUeCommon",
  "LteUeCommon",
  "LteUeCommon",
  "",
  sizeof(LteUeCommon),
  4,
  lte_ue_common__field_descriptors,
  lte_ue_common__field_indices_by_name,
  2,  lte_ue_common__number_ranges,
  (ProtobufCMessageInit) lte_ue_common__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ue_proc__field_descriptors[4] =
{
  {
    "CC_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UeProc, cc_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp_rx",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(UeProc, timestamp_rx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instance_cnt_synch",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UeProc, instance_cnt_synch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proc_rxtx",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UeProc, proc_rxtx),
    &ue_rx_tx_proc__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ue_proc__field_indices_by_name[] = {
  0,   /* field[0] = CC_id */
  2,   /* field[2] = instance_cnt_synch */
  3,   /* field[3] = proc_rxtx */
  1,   /* field[1] = timestamp_rx */
};
static const ProtobufCIntRange ue_proc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ue_proc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UeProc",
  "UeProc",
  "UeProc",
  "",
  sizeof(UeProc),
  4,
  ue_proc__field_descriptors,
  ue_proc__field_indices_by_name,
  1,  ue_proc__number_ranges,
  (ProtobufCMessageInit) ue_proc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue phy_vars_ue__ue_mode__enum_values_by_number[5] =
{
  { "NOT_SYNCHED", "PHY_VARS_UE__UE_MODE__NOT_SYNCHED", 0 },
  { "PRACH", "PHY_VARS_UE__UE_MODE__PRACH", 1 },
  { "RA_RESPONSE", "PHY_VARS_UE__UE_MODE__RA_RESPONSE", 2 },
  { "PUSCH", "PHY_VARS_UE__UE_MODE__PUSCH", 3 },
  { "RESYNCH", "PHY_VARS_UE__UE_MODE__RESYNCH", 4 },
};
static const ProtobufCIntRange phy_vars_ue__ue_mode__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex phy_vars_ue__ue_mode__enum_values_by_name[5] =
{
  { "NOT_SYNCHED", 0 },
  { "PRACH", 1 },
  { "PUSCH", 3 },
  { "RA_RESPONSE", 2 },
  { "RESYNCH", 4 },
};
const ProtobufCEnumDescriptor phy_vars_ue__ue_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "PhyVarsUe.UeMode",
  "UeMode",
  "PhyVarsUe__UeMode",
  "",
  5,
  phy_vars_ue__ue_mode__enum_values_by_number,
  5,
  phy_vars_ue__ue_mode__enum_values_by_name,
  1,
  phy_vars_ue__ue_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor phy_vars_ue__field_descriptors[40] =
{
  {
    "Mod_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, mod_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "CC_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, cc_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proc",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, proc),
    &ue_proc__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "no_timing_correction",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, no_timing_correction),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_total_gain_dB",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, tx_total_gain_db),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_total_gain_dB",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, rx_total_gain_db),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_power_max_dBm",
    17,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, tx_power_max_dbm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_connected_eNB",
    18,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, n_connected_enb),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ho_initiated",
    19,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, ho_initiated),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ho_triggered",
    20,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, ho_triggered),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frame_parms",
    22,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, frame_parms),
    &frameparms__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "common_vars",
    24,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, common_vars),
    &lte_ue_common__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_thread_id",
    25,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(PhyVarsUe, n_current_thread_id),
    offsetof(PhyVarsUe, current_thread_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "IMSImod1024",
    42,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, imsimod1024),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "PF",
    43,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, pf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "PO",
    44,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, po),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "UE_mode",
    48,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(PhyVarsUe, n_ue_mode),
    offsetof(PhyVarsUe, ue_mode),
    &phy_vars_ue__ue_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "high_speed_flag",
    54,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, high_speed_flag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "perfect_ce",
    55,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, perfect_ce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ch_est_alpha",
    56,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, ch_est_alpha),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "turbo_iterations",
    64,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, turbo_iterations),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "generate_prach",
    90,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, generate_prach),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prach_cnt",
    91,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, prach_cnt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prach_PreambleIndex",
    92,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, prach_preambleindex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "decode_SIB",
    93,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, decode_sib),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "decode_MIB",
    94,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, decode_mib),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_offset",
    95,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, rx_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_offset_diff",
    96,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, rx_offset_diff),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_sync_cell",
    97,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, time_sync_cell),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timing_advance",
    98,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, timing_advance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hw_timing_advance",
    99,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, hw_timing_advance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_secondary_ue",
    101,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, is_secondary_ue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "has_valid_precoder",
    102,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, has_valid_precoder),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "log2_maxp",
    104,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, log2_maxp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac_enabled",
    105,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, mac_enabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "init_averaging",
    106,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, init_averaging),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sinr_eff",
    109,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, sinr_eff),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "N0",
    110,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, n0),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transmission_mode",
    122,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(PhyVarsUe, n_transmission_mode),
    offsetof(PhyVarsUe, transmission_mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "turbo_cntl_iterations",
    173,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PhyVarsUe, turbo_cntl_iterations),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned phy_vars_ue__field_indices_by_name[] = {
  1,   /* field[1] = CC_id */
  13,   /* field[13] = IMSImod1024 */
  0,   /* field[0] = Mod_id */
  37,   /* field[37] = N0 */
  14,   /* field[14] = PF */
  15,   /* field[15] = PO */
  16,   /* field[16] = UE_mode */
  19,   /* field[19] = ch_est_alpha */
  11,   /* field[11] = common_vars */
  12,   /* field[12] = current_thread_id */
  25,   /* field[25] = decode_MIB */
  24,   /* field[24] = decode_SIB */
  10,   /* field[10] = frame_parms */
  21,   /* field[21] = generate_prach */
  32,   /* field[32] = has_valid_precoder */
  17,   /* field[17] = high_speed_flag */
  8,   /* field[8] = ho_initiated */
  9,   /* field[9] = ho_triggered */
  30,   /* field[30] = hw_timing_advance */
  35,   /* field[35] = init_averaging */
  31,   /* field[31] = is_secondary_ue */
  33,   /* field[33] = log2_maxp */
  34,   /* field[34] = mac_enabled */
  7,   /* field[7] = n_connected_eNB */
  3,   /* field[3] = no_timing_correction */
  18,   /* field[18] = perfect_ce */
  23,   /* field[23] = prach_PreambleIndex */
  22,   /* field[22] = prach_cnt */
  2,   /* field[2] = proc */
  26,   /* field[26] = rx_offset */
  27,   /* field[27] = rx_offset_diff */
  5,   /* field[5] = rx_total_gain_dB */
  36,   /* field[36] = sinr_eff */
  28,   /* field[28] = time_sync_cell */
  29,   /* field[29] = timing_advance */
  38,   /* field[38] = transmission_mode */
  39,   /* field[39] = turbo_cntl_iterations */
  20,   /* field[20] = turbo_iterations */
  6,   /* field[6] = tx_power_max_dBm */
  4,   /* field[4] = tx_total_gain_dB */
};
static const ProtobufCIntRange phy_vars_ue__number_ranges[15 + 1] =
{
  { 1, 0 },
  { 8, 2 },
  { 17, 6 },
  { 22, 10 },
  { 24, 11 },
  { 42, 13 },
  { 48, 16 },
  { 54, 17 },
  { 64, 20 },
  { 90, 21 },
  { 101, 31 },
  { 104, 33 },
  { 109, 36 },
  { 122, 38 },
  { 173, 39 },
  { 0, 40 }
};
const ProtobufCMessageDescriptor phy_vars_ue__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PhyVarsUe",
  "PhyVarsUe",
  "PhyVarsUe",
  "",
  sizeof(PhyVarsUe),
  40,
  phy_vars_ue__field_descriptors,
  phy_vars_ue__field_indices_by_name,
  15,  phy_vars_ue__number_ranges,
  (ProtobufCMessageInit) phy_vars_ue__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ue_rx_tx_proc__field_descriptors[19] =
{
  {
    "proc_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UeRxTxProc, proc_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cc_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UeRxTxProc, cc_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp_tx",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(UeRxTxProc, timestamp_tx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subframe_tx",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UeRxTxProc, subframe_tx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subframe_rx",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UeRxTxProc, subframe_rx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frame_tx",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UeRxTxProc, frame_tx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frame_rx",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UeRxTxProc, frame_rx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instance_cnt_rxtx",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UeRxTxProc, instance_cnt_rxtx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pthread_rxtx",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(UeRxTxProc, pthread_rxtx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instance_cnt_slot1_dl_processing",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UeRxTxProc, instance_cnt_slot1_dl_processing),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pthread_slot1_dl_processing",
    15,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(UeRxTxProc, pthread_slot1_dl_processing),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chan_est_pilot0_slot1_available",
    19,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UeRxTxProc, chan_est_pilot0_slot1_available),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chan_est_slot1_available",
    20,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UeRxTxProc, chan_est_slot1_available),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "llr_slot1_available",
    21,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UeRxTxProc, llr_slot1_available),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dci_slot0_available",
    22,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UeRxTxProc, dci_slot0_available),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "first_symbol_available",
    23,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(UeRxTxProc, first_symbol_available),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sub_frame_start",
    25,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UeRxTxProc, sub_frame_start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sub_frame_step",
    26,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UeRxTxProc, sub_frame_step),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gotIQs",
    27,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(UeRxTxProc, gotiqs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ue_rx_tx_proc__field_indices_by_name[] = {
  1,   /* field[1] = cc_id */
  11,   /* field[11] = chan_est_pilot0_slot1_available */
  12,   /* field[12] = chan_est_slot1_available */
  14,   /* field[14] = dci_slot0_available */
  15,   /* field[15] = first_symbol_available */
  6,   /* field[6] = frame_rx */
  5,   /* field[5] = frame_tx */
  18,   /* field[18] = gotIQs */
  7,   /* field[7] = instance_cnt_rxtx */
  9,   /* field[9] = instance_cnt_slot1_dl_processing */
  13,   /* field[13] = llr_slot1_available */
  0,   /* field[0] = proc_id */
  8,   /* field[8] = pthread_rxtx */
  10,   /* field[10] = pthread_slot1_dl_processing */
  16,   /* field[16] = sub_frame_start */
  17,   /* field[17] = sub_frame_step */
  4,   /* field[4] = subframe_rx */
  3,   /* field[3] = subframe_tx */
  2,   /* field[2] = timestamp_tx */
};
static const ProtobufCIntRange ue_rx_tx_proc__number_ranges[4 + 1] =
{
  { 1, 0 },
  { 14, 9 },
  { 19, 11 },
  { 25, 16 },
  { 0, 19 }
};
const ProtobufCMessageDescriptor ue_rx_tx_proc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UeRxTxProc",
  "UeRxTxProc",
  "UeRxTxProc",
  "",
  sizeof(UeRxTxProc),
  19,
  ue_rx_tx_proc__field_descriptors,
  ue_rx_tx_proc__field_indices_by_name,
  4,  ue_rx_tx_proc__number_ranges,
  (ProtobufCMessageInit) ue_rx_tx_proc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rx_tx_thread_data__field_descriptors[2] =
{
  {
    "proc",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RxTxThreadData, proc),
    &ue_rx_tx_proc__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ue",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RxTxThreadData, ue),
    &phy_vars_ue__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rx_tx_thread_data__field_indices_by_name[] = {
  0,   /* field[0] = proc */
  1,   /* field[1] = ue */
};
static const ProtobufCIntRange rx_tx_thread_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rx_tx_thread_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RxTxThreadData",
  "RxTxThreadData",
  "RxTxThreadData",
  "",
  sizeof(RxTxThreadData),
  2,
  rx_tx_thread_data__field_descriptors,
  rx_tx_thread_data__field_indices_by_name,
  1,  rx_tx_thread_data__number_ranges,
  (ProtobufCMessageInit) rx_tx_thread_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
